image: php:latest

cache:
  paths:
    - vendor

stages:
  - composer_check
  - analyze_code
  - tests

before_script:
  - apt-get update -yqq
  - apt-get install -yqq git
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
  - composer install

composer_check:
  stage: composer_check
  script:
    - composer validate && vendor/bin/security-checker security:check

analyze_code:
  stage: analyze_code
  script:
    - vendor/bin/phpcs --ignore-annotations --standard=PSR12 src tests && vendor/bin/phpstan analyse --level=max src tests

tests:
  stage: tests
  script:
    - vendor/bin/phpunit && vendor/bin/php-coverage-checker build/clover.xml 100
